# Generated by Django 5.0.7 on 2024-07-15 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Arzt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('web_seite', models.CharField(max_length=50)),
                ('medikamente', models.TextField(max_length=500)),
                ('tel', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.CharField(max_length=50)),
                ('alt', models.IntegerField()),
                ('patient_ty', models.CharField(choices=[('Ja', 'Ja'), ('Nein', 'Nein')], max_length=50)),
                ('medikamente', models.TextField(max_length=500)),
                ('arzt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_arzt', to='patienten.arzt')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_melder', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
