# Generated by Django 5.0.7 on 2024-07-15 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patienten', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='patient_ty',
        ),
        migrations.AddField(
            model_name='patient',
            name='krank',
            field=models.CharField(blank=True, choices=[('Ja', 'Ja'), ('Nein', 'Nein')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_situation',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
