# Generated by Django 5.0.7 on 2024-07-15 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patienten', '0002_remove_patient_patient_ty_patient_krank_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arzt',
            name='medikamente',
        ),
    ]
